linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_catches_without_on_clauses: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_js_rounded_ints: true
    avoid_renaming_method_parameters: true
    avoid_returning_null: true
    avoid_returning_this: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    comment_references: true
    implementation_imports: true
    lines_longer_than_80_chars: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    package_api_docs: true
    prefer_adjacent_string_concatenation: true
    prefer_expression_function_bodies: true
    prefer_int_literals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    public_member_api_docs: true
    sort_constructors_first: true
    tighten_type_of_initializing_formals: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: true
    use_to_and_as_if_applicable: true

analyzer:
  exclude:
    - lib/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
